// A list of all locales that are supported
export const locales = [
  'en',
  'de',
  'fr',
  'it',
  'nl',
  'pt',
  'es',
  'id',
  'ru',
  'tr',
  'ua',
  'hi',
  'he',
  'ar',
  'jp',
  'ko',
  'zh',
  'th',
  'da',
  'gr',
  'my',
  'no',
  'pl',
  'ro',
  'sv',
  'vi',
] as const;

export const langs = [
  { locale: 'en', name: 'English' },
  { locale: 'de', name: 'Deutsch' },
  { locale: 'fr', name: 'Français' },
  { locale: 'it', name: 'Italiano' },
  { locale: 'nl', name: 'Nederlands' },
  { locale: 'pt', name: 'Português' },
  { locale: 'es', name: 'Español' },
  { locale: 'id', name: 'Bahasa Indonesia' },
  { locale: 'ru', name: 'Русский' },
  { locale: 'tr', name: 'Türkçe' },
  { locale: 'ua', name: 'Українська' },
  { locale: 'hi', name: 'हिन्दी' },
  { locale: 'he', name: 'עברית' },
  { locale: 'ar', name: 'العربية' },
  { locale: 'jp', name: '日本語' },
  { locale: 'ko', name: '한국어' },
  { locale: 'zh', name: '中文' },
  { locale: 'th', name: 'ไทย' },
  { locale: 'da', name: 'Dansk' },
  { locale: 'gr', name: 'Ελληνικά' },
  { locale: 'my', name: 'Bahasa Melayu' },
  { locale: 'no', name: 'Norsk' },
  { locale: 'pl', name: 'Polski' },
  { locale: 'ro', name: 'Română' }, 
  { locale: 'sv', name: 'Svenska' },
  { locale: 'vi', name: 'Tiếng Việt' },
]
 
// ...